name: build image

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: latest
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: build multi-arch images
      run: |
        docker buildx build --push \
          --tag mcgunn/simprox:latest --tag mcgunn/simprox:$(echo $GITHUB_REF | sed 's|^refs/tags/v||') \
          --platform linux/amd64,linux/arm64 .
    - name: build multi-arch alpine images
      run: |
        docker buildx build --push \
          --tag mcgunn/simprox:latest --tag mcgunn/simprox:$(echo $GITHUB_REF | sed 's|^refs/tags/v||') \
          --platform linux/amd64,linux/arm64 .
